### ISSUE TITLE
When moving an AD to a different Category, the Expiration is not Updated

### ISSUE THREAD

**Issue by dimalif** [navjottomer/Osclass#41] opened 2019-08-24 11:27 UTC
Moving an ad from a category with X days expiration to an other category with Z days expiration, the ad expiration is NOT update. Remains X days.

This is a problem with the Stock Osclass 3.8 and this fork also.

**Comment by webmods-croatia** [comment] 2019-08-24 11:35
ItemActions.php, function edit(). What does this do?
```php
$dt_expiration = Item::newInstance()->updateExpirationDate($aItem['idItem'], $aItem['dt_expiration'], false
```

**Comment by dimalif** [comment] 2019-08-24 11:42
See the workaround and maybe you will understand better. I I have no idea about what that does, i'm not a programmer.

https://forums.osclass.org/3-8-x-43/expiration-dates-do-not-update/

**Comment by webmods-croatia** [comment] 2019-08-24 11:46
Ok, it's simple to fix this, but I don't quite get what the upper mentioned code does. Let's see if else response. @dev101

**Comment by dev-101** [comment] 2019-08-24 11:48
Personally, this is not something users usually do and you have to carefully think about what you want. Moving around items between categories with different duration may create confusion among users. I assume problem exists for categories that also have longer exp date (e.g. moving from 1 to 3 months)? In this case, items would be extended for 3 months without users knowing, so many items may long expire in real world.

I like the way it works now, btw.

One way is to add option (tick box) to update exp date to target category from the (date admin moves them to + exp_days) of target cat.

**Comment by dimalif** [comment] 2019-08-24 11:56
Users do not move their ads, correct. Webmasters do that daily. Several times. 

And if you move for example an ad about a JOB from a 365 days expiration category (that the user didn't select/know the duration), to the PROPER JOB category with a short 30 days expirtation, i think the 365 days should change to 30.

Because the categories have an expiration related to what the "are". Jobs 30 days, Cars 90 days, Personal 7 days, etc etc. 

What performance issue abd what large number of items ? I don't get it.

**Comment by dev-101** [comment] 2019-08-24 11:58
Ok, I thought you wont to do this in bulk in Admin... This can be fixed in item edit, in that case.

**Comment by dimalif** [comment] 2019-08-24 12:01
Well, all that could be solved if the users could actually select the duration. And that is already build in bender and core of Osclass, but for some reason it was never implemented. 

https://forums.osclass.org/general-help/can-somebody-pls-help-me-to-install-an-plugin-or-something-like-that/msg170281/#new

**Comment by dev-101** [comment] 2019-08-24 12:03
I fail to see connection, anyway, let's stay on topic ;)

**Comment by webmods-croatia** [comment] 2019-08-24 12:08
Not the best solution and code can be improved, but try this:

```php
function wm_item_category_update_expiration($item) {
    if(!OC_ADMIN) return;

    $category_id = $item['fk_i_category_id'];
    $category = Category::newInstance()->findByPrimaryKey($category_id);
    $category_expiration = $category['i_expiration_days'];

    $item_id = $item['pk_i_id'];
    $item_published = $item['dt_pub_date'];
    $item_expiration = $item['dt_expiration'];

    $new_expiration = new DateTime($item_published);
    $new_expiration->modify('+'.$category_expiration.' days');
    $new_expiration = $new_expiration->format('Y-m-d H:i:s');

    Item::newInstance()->updateByPrimaryKey(array('dt_expiration' => $new_expiration), $item_id);
}
```

**Comment by dev-101** [comment] 2019-08-24 12:17
You can remove admin check, so that users who change category also get affected.

**Comment by webmods-croatia** [comment] 2019-08-24 12:17
I removed it and I'm trying to test it but the function never gets called. Can you test?

**Comment by dev-101** [comment] 2019-08-24 12:18
(see my updated reply)

**Comment by dev-101** [comment] 2019-08-24 12:18
Your if condition must be if-else actually.

**Comment by webmods-croatia** [comment] 2019-08-24 12:19
Just made it so. :)

**Comment by dev-101** [comment] 2019-08-24 12:19
That should work. One final check, in core infinite exp date is compared to -1 for some reason, not 0.

**Comment by webmods-croatia** [comment] 2019-08-24 12:20
Is it possible that function isn't called because there's no actual theme? I added it in oc-includes/osclass/gui/functions.php

**Comment by webmods-croatia** [comment] 2019-08-24 12:21
> That should work. One final check, in core infinite exp date is compared to -1 for some reason, not 0.

In DB it's 0?

**Comment by dev-101** [comment] 2019-08-24 12:21
I think this must be added in active theme's functions.php, gui theme is just for backup.

**Comment by dev-101** [comment] 2019-08-24 12:21
Yes, that 0 in db is fine, just checked.

**Comment by dev-101** [comment] 2019-08-24 12:24
Final thing, move item[...] stuff all the way to top, in first if condition you pass itemId which is undefined.

**Comment by webmods-croatia** [comment] 2019-08-24 12:24
Yes, I just updated the code above.

**Comment by dev-101** [comment] 2019-08-24 12:25
Ok just saw it :)

**Comment by webmods-croatia** [comment] 2019-08-24 12:25
Can this be made any better?
`$new_expiration->modify('+'.$category_expiration.' days');`
It hurts watching it. ;)

**Comment by dev-101** [comment] 2019-08-24 12:32
You can simplify it like this (untested):

```
function wm_item_category_update_expiration($item) {
	$item_id = $item['pk_i_id'];
	$item_published = $item['dt_pub_date'];

	$category_id = $item['fk_i_category_id'];
	$category = Category::newInstance()->findByPrimaryKey($category_id);

	// infinite expiration date
	if ($category_expiration === 0) {
		Item::newInstance()->updateExpirationDate($item['fk_i_item_id'], '9999-12-31 23:59:59');
	// update expiration date
	} else {
		$update_expiration = date('Y-m-d H:i:s', strtotime($item['dt_pub_date']. ' + ' . $category['i_expiration_days'] . ' days'));
		Item::newInstance()->updateExpirationDate($item['fk_i_item_id'], $update_expiration);
	}
}
osc_add_hook('edited_item', 'wm_item_category_update_expiration');
```

**Comment by webmods-croatia** [comment] 2019-08-24 12:37
That works okay.

**Comment by dev-101** [comment] 2019-08-24 12:42
Ok, edited some copy-paste bugs, and minimzed to this new version. Please check if you can. Thanks!

**Comment by dev-101** [comment] 2019-08-24 12:47
One comment, I mentioned somewhere above that this should happen only on category change.
Above codes (all versions) will update the date every time items is edited, though. In terms of performance, I don't know... probably a bit slower this way, in case of category comparison, it will skip date 'refresh', but it is not that critical.

**Comment by webmods-croatia** [comment] 2019-08-24 12:49
"else {" - missing  a closing }

**Comment by dev-101** [comment] 2019-08-24 12:50
oops :)

**Comment by dimalif** [comment] 2019-08-24 12:50
@dev-101 so isn't it better to fix this in the core ? Because what i see is not a fix but something that must be added by the user.

**Comment by dev-101** [comment] 2019-08-24 12:52
Well, as I said, I don't use this... so for me it is not critical. It can be fixed in the core, though. Very easily. Wait until Navjot says what he wants to do... for me either way is OK.

**Comment by webmods-croatia** [comment] 2019-08-24 12:53
Not working if category expiration is 0. I think you should use

```php
Item::newInstance()->updateByPrimaryKey(array('dt_expiration' => $update_expiration), $item['fk_i_item_id']);
```

**Comment by dimalif** [comment] 2019-08-24 12:55
The no-expire is -1 from what i see in the code of Osclass.

**Comment by webmods-croatia** [comment] 2019-08-24 12:55
`if ($category['i_expiration_days'] === 0) {`
Not working with three "=".

**Comment by webmods-croatia** [comment] 2019-08-24 12:55
> The no-expire is -1 from what i see in the code of Osclass.

`$category['i_expiration_days']` returns 0.

**Comment by dev-101** [comment] 2019-08-24 12:56
Yeah, that's why I asked you about that 0... not sure now what Osclass returns (string or integer) there.

**Comment by dimalif** [comment] 2019-08-24 12:56
`tatic public function expiration_select($options = null)
        {
            if(OC_ADMIN) {
                if($options==null) { $options = array(-1,0,1,3,5,7,10,15,30); }`

**Comment by webmods-croatia** [comment] 2019-08-24 12:57
> Yeah, that's why I asked you about that 0... not sure now what Osclass returns (string or integer) there.

Seems it returns string.

Either `if ($category['i_expiration_days'] == 0) {` or `if ((int) $category['i_expiration_days'] === 0) {`

**Comment by dev-101** [comment] 2019-08-24 12:57
Yeah, but it returns -1, so I do remember it right.
Try -1 instead of 0 ?

**Comment by webmods-croatia** [comment] 2019-08-24 12:58
=== -1 not working.

**Comment by webmods-croatia** [comment] 2019-08-24 13:00
> `static public function expiration_select($options = null) { if(OC_ADMIN) { if($options==null) { $options = array(-1,0,1,3,5,7,10,15,30); }`

That is for category or item?

**Comment by webmods-croatia** [comment] 2019-08-24 13:02
`if (intval($category['i_expiration_days']) === 0) {` this works.

**Comment by webmods-croatia** [comment] 2019-08-24 13:03
`var_dump($category['i_expiration_days']);` - string(1) "0"

**Comment by webmods-croatia** [comment] 2019-08-24 13:04
`var_dump(intval($category['i_expiration_days']));` - int(0)

**Comment by dev-101** [comment] 2019-08-24 13:05
Ok, I will try === (int) 0

**Comment by dimalif** [comment] 2019-08-24 13:08
In Item.form.class.php  there is _static public function expiration_select_

**Comment by dimalif** [comment] 2019-08-24 13:09
`<?php foreach($options as $o) {
                        if($o==-1) {?>
                            options += '<option value="-1" >' + (osc.langs.nochange_expiration!=null?osc.langs.nochange_expiration:'<?php echo osc_esc_js(__('No change expiration')); ?>') + '</option>';
                        <?php } else if($o==0) { ?>
                            options += '<option value="" >' + (osc.langs.without_expiration!=null?osc.langs.without_expiration:'<?php echo osc_esc_js(__('Without expiration')); ?>') + '</option>';
                        <?php } else if($o==1) { ?>
                            options += '<option value="1" >' + (osc.langs.expiration_day!=null?osc.langs.expiration_day:'<?php echo osc_esc_js(__('1 day')); ?>')+ '</option>';
                        <?php } else { ?>
                            if(max_exp==0 || <?php echo $o; ?><=max_exp) {
                                options += '<option value="<?php echo $o; ?>" >' + (osc.langs.expiration_days!=null?osc.langs.expiration_days:'<?php echo osc_esc_js(__('%d days')); ?>').replace("%d", <?php echo $o; ?>) + '</option>';
                            }
                    <?php };`

**Comment by webmods-croatia** [comment] 2019-08-24 13:10
> In Item.form.class.php there is _static public function expiration_select_

That's for item expiration, here we talk about category expiration days.

**Comment by dev-101** [comment] 2019-08-24 13:16
Ok, I have no idea why it does not work... are you on dev server? Windows?
Anyway, == 0 comparison should be safe enough and that works. At least for me and you, so it should work fine. Not sure if this is a php particular version issue, or windows dll... have to run tests in different systems to be sure. But, overall, the code works ok.

**Comment by dimalif** [comment] 2019-08-24 13:16
@webmods-croatia I was only trying to help with the 0 and -1, and those are only set in the code i posted, nowhere else.

I mean the no-expire is set as -1.

**Comment by webmods-croatia** [comment] 2019-08-24 13:20
> Ok, I have no idea why it does not work... are you on dev server? Windows?
> Anyway, == 0 comparison should be safe enough and that works. At least for me and you, so it should work fine. Not sure if this is a php particular version issue, or windows exe/dll... have to run tests in different systems to be sure. But, overall, the code works ok.

VPS, CentOs 7, PHP 5.6.4, didn't update PHP yet because of other script I use there.

**Comment by dimalif** [comment] 2019-08-24 13:23
Guys i can test whatever is needed. Shall i put the code in theme or osclass functions ? And what code, since several have been posted here.

**Comment by webmods-croatia** [comment] 2019-08-24 13:23
****

> You can simplify it like this (untested):
> 
> ```
> function wm_item_category_update_expiration($item) {
> 	$category = Category::newInstance()->findByPrimaryKey($item['fk_i_category_id']);
> 
> 	if ($category['i_expiration_days'] === 0) {
> 		$update_expiration = '9999-12-31 23:59:59';
> 	} else {
> 		$update_expiration = date('Y-m-d H:i:s', strtotime($item['dt_pub_date'] . ' + ' . $category['i_expiration_days'] . ' days'));
> 	}
> 
> 	Item::newInstance()->updateExpirationDate($item['fk_i_item_id'], $update_expiration);
> }
> osc_add_hook('edited_item', 'wm_item_category_update_expiration');
> ```

Try this one, theme functions.

**Comment by dev-101** [comment] 2019-08-24 13:27
I don't really know, var_dump($category['i_expiration_days']) under XAMPP PHP 7.3 returns freaking empty string:

`'';`

Yes, this.

And under CloudLinux server (PHP 7.3.something) absolutely nothing. I am not sure what is happening, as if var_dump() wasn't even called. So, I am puzzled and will have to test this later, but overall, code is fine though.

**Comment by dimalif** [comment] 2019-08-24 13:29
The above seems to work fine. Both from the Admin dashboard and as a user (edit ad). 

No errors or notices or anything. Also the dates seem ok.

**Comment by webmods-croatia** [comment] 2019-08-24 13:30
Maybe it's related to my PHP 5.6, I will try with PHP 7.

**Comment by dimalif** [comment] 2019-08-24 13:32
Oops. I was very quick to report.

There is a **delay in everything** and an error:

PHP Notice:  Array to string conversion in /home/oc-includes/osclass/classes/database/DBCommandClass.php on line 334

**Comment by webmods-croatia** [comment] 2019-08-24 13:33
Can we just use == 0?

**Comment by dev-101** [comment] 2019-08-25 00:26
> > Yeah, that's why I asked you about that 0... not sure now what Osclass returns (string or integer) there.
> 
> Seems it returns a string.

Yes, you were correct here. Finally had some piece time and figured it all out (including my mysterious issue with var_dump). It is, indeed, a string, which means that it is directly pulled from db without any formatting in the core. That was the cause of all the trouble. Final version updated.

**Closed** 2019-10-29 22:25 UTC
