### ISSUE TITLE
PHP 7.2 - Adding images - Uncaught Error: Cannot use string offset as an array

### ISSUE THREAD

**Issue by webmods-croatia** [navjottomer/Osclass#36] opened 2019-08-18 09:08 UTC
When adding images to an item while using PHP 7.2, this appears in debug.log:
> Uncaught Error: Cannot use string offset as an array

To fix it, in file [oc-includes/osclass/ItemActions.php:1172](https://github.com/navjottomer/Osclass/blob/master/oc-includes/osclass/ItemActions.php)

change

```php
if(is_array($ajax_photos)) {
```

to

```php
if(is_array($ajax_photos)) {
    if ($aItem['photos'] === '') {
        $aItem['photos'] = array();
    }
```

**NOTE:** This was found out by @marius-ciclistu on Osclass Community forums.

**Comment by dimalif** [comment] 2019-08-18 11:01
Can't replicate it. Works for me. PHP 7.2.21, Bender, develop version

**Comment by marius-ciclistu** [comment] 2019-08-18 11:07
Anyway it should be fixed one way or another. It's not ok to make string[]=something.

**Comment by dev-101** [comment] 2019-08-18 22:25
Maybe we should use empty() check instead === '', in case $aItem['photos'] is not set (can that be the case?), because it will generate a different notice in that case.

**Comment by marius-ciclistu** [comment] 2019-08-19 03:05
As I don't use plugins, getFiles returns empty string. is_array()=== false could be used, empty returns strange things in special cases.

**Comment by navjottomer** [comment] 2019-08-19 06:26
We can add check like this
```php
 if(is_array($ajax_photos) && (sizeof($ajax_photos) > 0) )
```
BTW I am not able to reproduce it.

**Comment by mkraha** [comment] 2019-08-19 07:55
> 
> BTW I am not able to reproduce it.
Just to know, What you mean for "REPRODUCE" here?

**Comment by navjottomer** [comment] 2019-08-19 08:00
> > BTW I am not able to reproduce it.
> 
> Just to know, What you mean for "REPRODUCE" here?

This error.

**Comment by marius-ciclistu** [comment] 2019-08-19 09:14
I have.7.2.19 if I remember right. Sizeof is not necessary. Empty array is ok.

**Comment by marius-ciclistu** [comment] 2019-08-19 09:21
Is_array($aItem['photos']) === false
Then $aItem['photos']=array();

**Comment by dev-101** [comment] 2019-08-19 09:33
Keep in mind that certain PHP versions have bugs. Update to latest 7.2.x or 7.3.x and then check if it happens again.

https://www.php.net/ChangeLog-7.php#PHP_7_2

**Comment by navjottomer** [comment] 2019-08-19 09:47
No need to define ```php $aItem['photos'] = array(); ```
It's already defined if no file is uploaded by ```php Params::getFiles('photos');``` 
Adding a check for empty ```php $ajax_photos ``` still recommended.
I'll add it in next commit. I am closing this issue.

**Comment by marius-ciclistu** [comment] 2019-08-19 09:48
I'll not update on my local server as the latest is not the best from my experience :) I fixed my code. If the issue is not seen as an issue by this comunity It's not my problem :). 
$aItem['photos']="" in my case, so
 ""[]= something 
Is not ok.

**Closed by navjottomer** 2019-08-19 09:47 UTC

**Comment by navjottomer** [comment] 2019-08-19 15:07
> I'll not update on my local server as the latest is not the best from my experience :) I fixed my code. If the issue is not seen as an issue by this comunity It's not my problem :).
> $aItem['photos']="" in my case, so
> ""[]= something
> Is not ok.

I can't fix a bug which I can't reproduce. BTW as I said ```$aItem['photos']``` is already set as an empty array. Why do we need to do this again?
Let me know if I misunderstood your issue.

**Comment by marius-ciclistu** [comment] 2019-08-19 17:10
Could be that getFiles, only in my case sets  
$aItem['photos'] to empty string... And indeed. Thanks for the heads-up.
