### ISSUE TITLE
Freezing in admin when Osclass.org is down using the current dev version

### ISSUE THREAD

**Issue by dimalif** [navjottomer/Osclass#64] opened 2019-09-23 10:42 UTC
The last 3 days Osclass.org is down (504 Gateway Time-out). Using the development version, when log in in admin dashboard i experience a huge delay, something like 1 or even 2 minutes. A freeze in the admin dashboard, in every option we try to select. 

This seems to go away after a while, and a second login to the admin seems ok. 

If the dev version has included the disabling of Market, then the problem is **NOT** the Osclass Market beeing down, but some other connection with Osclass.org.

**Comment by dimalif** [comment] 2019-09-23 11:27
Actually Osclass.org being down, makes us a favor. We can do all kind of test for all that. I mean what happens when they fully disappear.

**Comment by Tangol** [comment] 2019-09-23 20:45
I can confirm the issue.
It happens both in the **admin** and **homepage**.

**Comment by eurobank** [comment] 2019-09-23 20:57
I don't think it happens in any page that is for users or visitors. Not 100% about it, since it can't be easily measured.

**Comment by Tangol** [comment] 2019-09-23 21:11
I have a wild guess it's related to these:
https://github.com/navjottomer/Osclass/blob/develop/oc-includes/osclass/utils.php#L1992
https://github.com/navjottomer/Osclass/blob/develop/oc-includes/osclass/utils.php#L2126
https://github.com/navjottomer/Osclass/blob/develop/oc-admin/themes/modern/tools/upgrade.php#L44

**Comment by eurobank** [comment] 2019-09-23 21:57
@tangol all that i think they are related to admin dashboard functions. The only thing a visitor at home page can do is trigger a cron.

**Comment by Tangol** [comment] 2019-09-24 13:58
@eurobank for me the issue was much worse.
I couldn't even access the plugins or themes. After 2-3 minutes of loading, it would return a blank page.
Also, it seemed it affected the homepage as well, as I was getting a much slower response time.

@navjottomer any thoughts on this?

**Comment by navjottomer** [comment] 2019-09-24 19:16
I didn't encounter any slow-down at my local installation( dev-branch) yet. But I think the reliance on the remote server in main execution thread is a culprit for this issue, we need to add more ajax methods to communicate with remote servers. 
Removing remote calls (and convert them to ajax calls if possible) from php-script while rendering is an only solution for such slowdown.

**Comment by dev-101** [comment] 2019-09-24 19:27
Try these changes, I have encountered on initial admin login after couple of hours (might not work if already logged-in):

https://github.com/dev-101/Osclass/commit/8adfc9a616f9722291f6dba468928655aff81e31
https://github.com/dev-101/Osclass/commit/1da7d67627cdbb4006dc99ee796243d406dd2957
https://github.com/dev-101/Osclass/commit/1a79edba5692039d495f3900a3a590af063b5776

**Comment by navjottomer** [comment] 2019-09-24 20:01
These changes are already done in current dev build.

**Comment by Tangol** [comment] 2019-09-24 20:08
At the moment everything related to Osclass is down:
- https://geo.osclass.org/
- https://osclass.org/
- https://forums.osclass.org/

Fixed the freezing issue with:
- https://docs.osclasscommunity.com/removing-market/remove-calls-to-osclass/delete-featured-products-from-admin.
- https://docs.osclasscommunity.com/removing-market/remove-calls-to-osclass/stop-checking-for-updates-from-osclass
- https://docs.osclasscommunity.com/removing-market/remove-calls-to-osclass/stop-auto-upgrading
- https://docs.osclasscommunity.com/removing-market/remove-calls-to-osclass/disable-upgrade-page

Some of the above are not present in the current dev build.

**Comment by navjottomer** [comment] 2019-09-24 21:01
Related https://github.com/navjottomer/Osclass/commit/7e6afce52a88a5c79c513e9a466510362bf65325

**Comment by webmods-croatia** [comment] 2019-09-26 16:54
I'm running a few sites with fixes listed here: "https://docs.osclasscommunity.com/removing-market/" with no problems.

I applied the same fixes in a pull request that's been merged into develop branch.

**Comment by webmods-croatia** [comment] 2019-09-28 12:51
@navjottomer I think a new version should be released with Market changes applied.

**Closed** 2019-10-07 19:10 UTC
